### ISSUE TITLE
Kernel Equivariance over group

### ISSUE THREAD

**Issue by ch-ho00** [ebekkers/gsplinets#1]
Hi. First of all thank you for the great work and open sourcing the code! 
I had a question regarding the theoretical aspect embedded in the code. So from what I see from the code, it seems like the B spline basis is formulated based on the arguments (xx_basis_scale, xx_basis_size, etc) which are combined to form the kernel (as it is the whole idea of the model).

My question is how does the model learn to become equivariant over the group being considered? The initialization of the weights of the coefficients is xavier_initializer which is a normal distribution with mean 0. 

I see that lines such as
```
        return (1/self.H.det(h))*Kernel( self.H.left_action_on_Rn( self.H.inv(h), self.xx_grid ) )

        return (1/self.H.det(h))*Kernel( self.H.left_action_on_Rn( h_inv, self.xx_grid ), self.H.prod(h_inv, self.input_h_grid.grid) )

```
aims to transform the original kernel for group convolution on the inputs of (xx_grid and/or input_h_grid).

So how does this lead to the kernel being able to satisfy the constraints stated in the paper (thm1 and corollary)?

Once again, thank you for the work and looking forward for the reply!

**Comment by ch-ho00** [comment]
I noticed that inverse of det of h and left action on  x does imply the constrains being satisfied. Sorry about the confusion.

**Comment by ebekkers** [comment]
That's correct, and no problem! The paper/code follow each other quite closely I think. The general routing is: transform the spatial grid and sub-group grid via resp the group action and group product, then sample the kernel on it and apply the convolutions (for each h). Don't hesitate to submit questions or mail me directly. Erik
